# Generated by Django 6.0.5 on 2026-05-20 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nu', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('adress', models.CharField()),
            ],
        ),
    ]
